<div class="row">
    <div class="col-md-3">
        <div class="list-group">
            <a href="/servicos/web" title="web" class="list-group-item">WEB</a>
            <a href="/servicos/automacao" title="Automaçao" class="list-group-item">Automaçao</a>
            <a href="/servicos/mobile" title="Tablets e Smartphones" class="list-group-item">Mobile</a>
            <a href="/servicos/consultoria" title="Consultoria" class="list-group-item">Consultoria</a>
            <a href="/servicos/Manutencao" title="Manutençao" class="list-group-item">Manutençao</a>
            <a href="/servicos/redes" title="Redes" class="list-group-item">Redes</a>
            <a href="/servicos/seo" title="SEO" class="list-group-item">SEO</a>
            <a href="/servicos/cursos" title="Cursos" class="list-group-item">Cursos</a>
        </div>
    </div>
    <div class="col-md-9">
        <?php echo $this->getContent(); ?>
    </div>
</div>