<div class="row">
    <div class="col-md-4">
        <h2>WEB</h2>
        <p>Hospedagem e desenvolvimetos de sites e sistemas para sua empresa. Utilizamos as tecnologias mais recentes e seguras para garanti nossos serviços.</p>
        <p><a class="btn btn-default" href="/servicos/web" role="button">Leia mais &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>AUTOMAÇAO</h2>
        <p>Trabalhamos com solunçoes diversas em automaçao para residencias, sistemas de produçao de alimentos, comercios, sistemas de segurança e cronometragem de corridas</p>
        <p><a class="btn btn-default" href="/servicos/automacao" role="button">Leia mais &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>MOBILE</h2>
        <p>Desenvolvemos aplicaçoes para Android, IOs, Windows Phone e Firefox OS.</p>
        <p><a class="btn btn-default" href="/servicos/mobile" role="button">Leia mais &raquo;</a></p>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>CURSOS</h2>
        <p>Hospedagem e desenvolvimetos de sites e sistemas para sua empresa. Utilizamos as tecnologias mais recentes e seguras para garanti nossos serviços.</p>
        <p><a class="btn btn-default" href="/servicos/cursos" role="button">Leia mais &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>MANUTEÇAO</h2>
        <p>Trabalhamos com solunçoes diversas em automaçao para residencias, sistemas de produçao de alimentos, comercios, sistemas de segurança e cronometragem de corridas</p>
        <p><a class="btn btn-default" href="/servicos/manutencao" role="button">Leia mais &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>VENDAS</h2>
        <p>Desenvolvemos aplicaçoes para Android, IOs, Windows Phone e Firefox OS.</p>
        <p><a class="btn btn-default" href="/loja" role="button">Leia mais &raquo;</a></p>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>REDES</h2>
        <p>Hospedagem e desenvolvimetos de sites e sistemas para sua empresa. Utilizamos as tecnologias mais recentes e seguras para garanti nossos serviços.</p>
        <p><a class="btn btn-default" href="/servicos/redes" role="button">Leia mais &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>CONSULTORIA</h2>
        <p>Trabalhamos com solunçoes diversas em automaçao para residencias, sistemas de produçao de alimentos, comercios, sistemas de segurança e cronometragem de corridas</p>
        <p><a class="btn btn-default" href="/servicos/consultoria" role="button">Leia mais &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>OTIMIZAÇAO SEO</h2>
        <p>Desenvolvemos aplicaçoes para Android, IOs, Windows Phone e Firefox OS.</p>
        <p><a class="btn btn-default" href="/servicos/seo" role="button">Leia mais &raquo;</a></p>
    </div>
</div>