<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->tag->getTitle() ?>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <!-- Optional theme -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.2.0/cerulean/bootstrap.min.css">
    </head>
    <body>

        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Painel de Controle</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/servicos">Configuraçoes</a></li>
                        <li><a href="/quem-somos">Comunicaçoes</a></li>
                        <li><a href="/contatos">Serviços</a></li>
                        <li><a href="/contatos">Loja</a></li>
                        <li><a href="/contatos">Finanças</a></li>
                    </ul>
                    <ul class="nav navbar-right">
                        <li><a href="/sair">Sair</a></li>
                    </ul>
                </div><!--/.navbar-collapse -->
            </div>
        </div>
        <div class="container">
            <?php echo $this->getContent(); ?>
            <hr>
            <footer>
                <p>&copy; LR Host 2014. Todos os direitos reservados</p>
            </footer>
        </div> <!-- /container -->
        <!-- jQuery (necessary for 1Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </body>
</html>